services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
    ports:
      - "5432:5432"
    secrets:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    networks:
      - sm_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  POSTGRES_DB:
    external: true
  POSTGRES_PASSWORD:
    external: true
  POSTGRES_USER:
    external: true

volumes:
  postgres_storage:
    driver: local

networks:
  sm_network:
    external: true