auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  #instance_addr: loki
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  chunk_idle_period: 1h
  max_chunk_age: 1h
  lifecycler:
    address: 0.0.0.0
    final_sleep: 0s
    ring:
      replication_factor: 1
      kvstore:
        store: inmemory
    tokens_file_path: ""

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h

ruler:
  alertmanager_url: http://alertmanager:9093

analytics:
  reporting_enabled: false